// Auto-generated by OpenLane
module pm32(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input start,
  input[31:0] mc,
  input[31:0] mp,
  output[63:0] p,
  output done
);
endmodule
